baseURL = "https://today.dedenf.com/"
languageCode = "en-us"
title = "Today i did and learn ..."
theme = "hugo-paper"

[build]
publish = "public"
command = "hugo"

[context.production.environment]
HUGO_VERSION = "0.49.2"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --buildFuture -b $DEPLOY_PRIME_URL"